# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'
gem 'rails', '6.0.3.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# Use Puma as the app server
gem 'active_model_serializers'
gem 'activerecord-import', '~> 0.15.0'
gem 'colorize', '~> 0.8.1'
gem 'devise'
gem 'devise_token_auth', '~> 1.1.5'
gem 'dotenv-rails', '~> 2.1', '>= 2.1.1'
gem 'pg', '~> 1.2.3'
gem 'puma', '= 5.2.2'
gem 'settingslogic'
gem 'rack-cors', require: 'rack/cors'
gem 'redis'
gem 'redis-namespace', '~> 1.5', '>= 1.5.2'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'virtus'
gem 'wisper', '2.0.0'
gem 'data_migrate'
gem 'will_paginate'
gem 'pg_search'
gem 'carrierwave', '~> 2.0'
gem 'fog-aws'
gem 'paranoia', '~> 2.2'
gem 'unread'
gem 'google-api-client'
gem 'googleauth'
gem 'stripe'
gem 'drill-mailer'
gem 'letter_opener_web', '~> 1.0'
gem 'letter_opener'


# for elasticbeanstalk fixes
gem 'nio4r', '2.5.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2' #, require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'awesome_print'
  gem 'pry'
  gem 'pry-rails'
  gem 'query_count'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'wisper-rspec'
  gem 'rubocop-rspec'
  gem 'bullet'
end

group :development do
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'graphviz', '~> 0.3.0'
  gem 'rails-erd', '~> 1.5', '>= 1.5.2'
  gem 'rubocop', require: false
  gem 'rubocop-rails'
end

group :test do
  gem 'database_cleaner'
  gem 'webmock'
  gem 'factory_bot_rails'
  gem 'faker', '~> 1.6', '>= 1.6.6'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'rubocop-performance', '~> 1.14'

gem 'rubocop-rake', '~> 0.6.0'
