import colors from 'lib/theme/colors';
import { makeStyles } from '@material-ui/core/styles';

const materialStyles = makeStyles((theme) => ({
  addChallengeButton: {
    display: 'flex',
    flexDirection: 'row',
    width: '200px',
  },
  addChallengeCloseButton: {
    marginRight: 0,
  },
  addChallengeDatePickBox: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  addChallengeDateTitleText: {
    color: colors.gray500,
    fontFamily: "'Roboto', sans-serif",
    fontSize: 20,
  },
  addChallengeFieldWrapper: {
    margin: '3px',
    width: '100%',
  },
  addChallengeFooterCenter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '33%',
  },
  addChallengeFooterLeft: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: '33%',
  },
  addChallengeFooterRight: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'end',
    width: '34%',
  },
  addChallengeFormWrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    justifyContent: 'space-between',
    width: '100%',
  },
  addChallengeRangePicker: {
    width: '100%',
  },
  addChallengeRangePickWrapper: {
    all: 'unset',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  addChallengeTitle: {
    color: colors.darkPink,
    fontFamily: "'Roboto', sans-serif",
    fontSize: 28,
  },
  challengeAdminContent: {
    display: 'flex',
    flexDirection: 'column',
    paddingBottom: '30px',
    paddingTop: '30px',
    width: '100%',
  },
  challengeApprovalBarButtons: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  challengeCalendarDayColorDefault: {
    backgroundColor: '#FFFFFF',
    radius: '50%',
  },
  challengeCalendarDayColorUnverified: {
    backgroundColor: 'yellow',
    radius: '50%',
  },
  challengeCalendarDayColorVerified: {
    backgroundColor: 'green',
    radius: '50%',
  },
  challengeCalendarHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  challengeCalendarMain: {
    width: '100%',
  },
  challengeCalendarMainWrapper: {
    maxHeight: '100%',
    padding: 0,
    width: '100%',
  },
  challengeCalendarParticipantBar: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  challengeCalendarParticipantBarCheckInCount: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  challengeCalendarParticipantBarIconName: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: '75%',
  },
  challengeCalendarParticipantBarName: {
    display: 'flex',
    flexDirection: 'row',
    fontSize: 18,
    marginLeft: 5,
    textAlign: 'center',
    verticalAlign: 'middle',
    alignItems: 'center',
  },
  challengeCalendarParticipantBarComment: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: 16,
    paddingLeft: '3px',
  },
  challengeCalendarDate: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    fontFamily: "'Roboto', sans-serif",
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    alignItems: 'center',
  },
  challengeCalendarParticipantBarWrapper: {
    background: '#F9F9F9',
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: '4px',
  },
  challengeCalendarParticipantSearch:{ 
    borderRadius: '3px',
    marginTop: '3px',
    marginBottom: '3px',
  },
  challengeCalendarSelectUserButton: {
    background: '#F9F9F9',
    borderRadius: 0,
  },
  challengeCalendarShowMoreButtonWrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    justifyContent: 'center',
  },
  challengeCalendarUserDisplay: {
    alignItems: 'center',
    border: '1px solid',
    borderRadius: 0,
    borderStyle: 'solid none solid solid',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  challengeCheckInApprovalBar: {
    border: '2px solid black',
    borderRadius: '10px',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: '5px',
    padding: '5px',
    width: '100%',
  },
  challengeCheckInApprovalBarNoneFound: {
    border: '2px solid black',
    borderRadius: '10px',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: '5px',
    padding: '5px',
    width: '100%',
    fontSize: 16,
    alignItems: 'center',
    minHeight: '50px',
    paddingLeft: '10px',
  },
  challengeCheckInApprovalFooter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
  },
  challengeCheckInApprovalHeader: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: '15px',
    marginTop: '10px',
    width: '100%',
  },
  challengeCheckInApprove: {
    backgroundColor: 'green',
    borderRadius: '50%',
    height: '50px',
    margin: '10px',
    padding: 0,
    radius: 0,
    width: '50px',
  },
  challengeCheckInDeny: {
    backgroundColor: 'red',
    borderRadius: '50%',
    height: '50px',
    matgin: '10px',
    padding: 0,
    radius: 0,
    width: '50px',
  },
  challengeCheckinFieldWrapper: {
    margin: '3px',
    width: '100%',
  },
  challengeCheckinFieldWrapper: {
    margin: '3px',
    width: '100%',
  },
  challengeContentBody: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: 16,
    paddingLeft: 5,
    textAlign: 'left',
    whiteSpace: 'pre-wrap',
    marginBottom: '10px',
  },
  challengeContentExtras: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: 16,
    paddingLeft: 5,
    textAlign: 'left',
  },
  challengeContentHeader: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: 20,
    paddingLeft: 5,
    textAlign: 'left',
  },
  challengeDescriptionWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginTop: '10px',
    marginBottom: '10px',
    border: `1px solid ${colors.darkPink}`,
    borderRadius: '10px',
    padding: '3px',
  },
  challengeEnroll: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    margin: 0,
    padding: 0,
    width: '100%',
  },
  challengeCheckInButton:{
    marginTop: '10px',
    marginBotton: '10px',
  },
  challengeEnrollPadding: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '33%',
  },
  challengeEnrollPaddingRight: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'right',
    width: '33%',
  },
  challengeEntry1: {
    backgroundColor: 'white',
    border: '0px',
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 5,
    paddingRight: 5,
    width: '100%',
  },
  challengeEntry2: {
    backgroundColor: '#D3D3D3',
    border: '0px',
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 5,
    paddingRight: 5,
    width: '100%',
  },
  challengeEntryName: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  challengeEntryNames: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  challengeEntryParticipantCount: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'right',
  },
  challengeEntrySelected1: {
    backgroundColor: 'white',
    border: `2px solid ${colors.darkPink}`,
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 5,
    paddingRight: 5,
    width: '100%',
  },
  challengeEntrySelected2: {
    backgroundColor: '#D3D3D3',
    border: `2px solid ${colors.darkPink}`,
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 5,
    paddingRight: 5,
    width: '100%',
  },
  challengeEntryUsername: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: 12,
    fontWeight: 'normal',
    textAlign: 'left',
  },
  challengeList: {
    display: 'flex',
    flexDirection: 'column',
    //overflow: 'auto',
    //overflowY: 'scroll',
  },
  challengeListHeader: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: 20,
    paddingLeft: 5,
    textAlign: 'left',
  },
  challengeListSearchButton: {
    backgroundColor: '#F0F0F0',
    borderRadius: 0,
    width: '16%',
  },
  challengeListSearchButtonSelected: {
    backgroundColor: '#D1D1D1',
    borderRadius: 0,
    width: '16%',
  },
  challengeListSelectorButton1: {
    backgroundColor: '#F0F0F0',
    borderRadius: 0,
    borderStyle: 'solid none solid solid',
    width: '18%',
  },
  challengeListSelectorButton1Selected: {
    backgroundColor: '#D1D1D1',
    borderRadius: 0,
    borderStyle: 'solid none solid solid',
    width: '18%',
  },
  challengeListSelectorButton2: {
    backgroundColor: '#F0F0F0',
    borderRadius: 0,
    borderStyle: 'solid none solid solid',
    width: '35%',
  },
  challengeListSelectorButton2Selected: {
    backgroundColor: '#D1D1D1',
    borderRadius: 0,
    borderStyle: 'solid none solid solid',
    width: '35%',
  },
  challengeListSelectorButton3: {
    backgroundColor: '#F0F0F0',
    borderRadius: 0,
    borderStyle: 'solid none solid solid',
    width: '31%',
  },
  challengeListSelectorButton3Selected: {
    backgroundColor: '#D1D1D1',
    borderRadius: 0,
    borderStyle: 'solid none solid solid',
    width: '31%',
  },
  challengeListSelectorButtons: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: '100%',
  },
  challenges: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    maxHeight: '200%',
    width: '100%',
    marginRight: '2px',
  },
  ChallengeTitle: {
    borderStyle: 'none none solid none',
    color: colors.darkPink,
    fontFamily: "'Roboto', sans-serif",
    fontSize: 36,
    fontWeight: 700,
    marginBottom: 1,
    paddingBottom: 0,
  },
  challengeVideo: {
    height: '100%',
    left: 0,
    position: 'absolute',
    top: 0,
    width: '100%',
  },
  challengeVideoWrapper: {
    height: 0,
    paddingBottom: '56.25%',
    position: 'relative',
  },
  columnFlex: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  challengeCalendarCheckInBarWrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    marginTop: '5px',
  },
  columnFlexSpaceBetween: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    justifyContent: 'space-between',
  },
  columnFlexStart: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    justifyContent: 'flex-start',
  },
  currentChallenge: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    marginLeft: '2px',
  },
  editChallengeButton: {
    display: 'flex',
    flexDirection: 'row',
    width: '200px',
  },
  editChallengeCloseButton: {
    marginRight: 0,
  },
  editChallengeDatePickBox: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  editChallengeDateTitleText: {
    color: colors.gray500,
    fontFamily: "'Roboto', sans-serif",
    fontSize: 20,
  },
  editChallengeFieldWrapper: {
    margin: '3px',
    width: '100%',
  },
  editChallengeFooterCenter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '33%',
  },
  editChallengeFooterLeft: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: '33%',
  },
  editChallengeFooterRight: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'end',
    width: '34%',
  },
  editChallengeFormWrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    justifyContent: 'space-between',
    width: '100%',
  },
  editChallengeRangePicker: {
    width: '100%',
  },
  editChallengeRangePickWrapper: {
    all: 'unset',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  editChallengeTitle: {
    color: colors.darkPink,
    fontFamily: "'Roboto', sans-serif",
    fontSize: 28,
  },
  formButtonNotSelected: {
    border: '1px solid',
    borderRadius: 0,
    width: '20%',
  },
  formButtonSelected: {
    backgroundColor: colors.darkPink,
    border: '1px solid',
    borderRadius: 0,
    width: '20%',
  },
  rowFlexSpaceBetween: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  rowFlexFlexStart: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: '100%',
  },
  viewChallengeBackground: {
    display: 'flex',
    flexDirection: 'row',
    width: '75%',
    marginTop: 0,
    paddingTop: 0,
    paddingLeft: 0,
    paddingRight: '25%',
  },
  viewChallengeWrapper: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    padding: 0,
    margin: 0,
  },
  viewChallengeLeftBox: {
    display: 'flex',
    flexDirection: 'flex-start',
    justifyContent: 'flex-start',
    alignItems: 'left',
    width: '25%',
    padding: 0,
    margin: 0,
  },
  viewChallenges: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    margin: 2,
    marginBottom: '20px',
    marginTop: 0,
    maxHeight: '100%',
    maxWidth: '100%',
    minWidth: '50%',
  },
  viewChallengesWrapper: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    marginRight: '10px',
    marginTop: 0,
    maxHeight: '100%',
    maxWidth: '100%',
    minWidth: '50%',
    padding: 0,
  },
}));

export default materialStyles;
