version: "3.9"
services:
  app:
    image: xalt-backend
    env_file: ../.env
    restart: always
    ports:
      - 3000:3000
  sidekiq:
    image: xalt-backend
    env_file: ../.env
    restart: always
    command: bundle exec sidekiq -e production -C config/sidekiq.yml
