default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: xalt_dev
  template: template0

test:
  <<: *default
  database: xalt_test
  template: template0

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'xalt_dev' } %>
  template: template0
