name: s3-depl

on:
  push:
    branches:
      - production

jobs:
  build:
    env:
      API_URL: https://api-staging1.xalt.ai
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Yarn install
        run: |
          yarn install
          echo "VIMEO_ACCESS_TOKEN=8f774fc0c6861fe3e5a706247fb0cf7b" >> .env
      - name: Build
        run: yarn build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./dist/ s3://prod-xalt-fe --delete
