const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT = 'LOGOUT';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_ERROR = 'SIGNUP_ERROR';
const FINISH_ONBOARDING_REQUEST = 'FINISH_ONBOARDING_REQUEST';
const FINISH_ONBOARDING_SUCCESS = 'FINISH_ONBOARDING_SUCCESS';
const FINISH_ONBOARDING_ERROR = 'FINISH_ONBOARDING_ERROR';
const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
const CONFIRM_RESET_PASSWORD_REQUEST = 'CONFIRM_RESET_PASSWORD_REQUEST';
const CONFIRM_RESET_PASSWORD_SUCCESS = 'CONFIRM_RESET_PASSWORD_SUCCESS';
const CONFIRM_RESET_PASSWORD_ERROR = 'CONFIRM_RESET_PASSWORD_ERROR';
const SET_IS_SIGNUP_SUCCEEDED = 'SET_IS_SIGNUP_SUCCEEDED';
const CREATE_STRIPE_LINK_REQUEST = 'CREATE_STRIPE_LINK_REQUEST';
const CREATE_STRIPE_LINK_SUCCESS = 'CREATE_STRIPE_LINK_SUCCESS';
const CREATE_STRIPE_LINK_ERROR = 'CREATE_STRIPE_LINK_ERROR';
const CLEAR_STRIPE_LINK = 'CLEAR_STRIPE_LINK';

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGOUT,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  FINISH_ONBOARDING_REQUEST,
  FINISH_ONBOARDING_SUCCESS,
  FINISH_ONBOARDING_ERROR,
  RESET_PASSWORD_REQUEST,
  RESET_PASSWORD_SUCCESS,
  RESET_PASSWORD_ERROR,
  CONFIRM_RESET_PASSWORD_REQUEST,
  CONFIRM_RESET_PASSWORD_SUCCESS,
  CONFIRM_RESET_PASSWORD_ERROR,
  SET_IS_SIGNUP_SUCCEEDED,
  CREATE_STRIPE_LINK_REQUEST,
  CREATE_STRIPE_LINK_SUCCESS,
  CREATE_STRIPE_LINK_ERROR,
  CLEAR_STRIPE_LINK,
};
