const GET_COACH_PROFILES_REQUEST = 'GET_COACH_PROFILES_REQUEST';
const GET_COACH_PROFILES_SUCCESS = 'GET_COACH_PROFILES_SUCCESS';
const GET_COACH_PROFILES_ERROR = 'GET_COACH_PROFILES_ERROR';
const CLEANUP_COACH_PROFILES = 'CLEANUP_COACH_PROFILES';

export default {
  GET_COACH_PROFILES_REQUEST,
  GET_COACH_PROFILES_SUCCESS,
  GET_COACH_PROFILES_ERROR,
  CLEANUP_COACH_PROFILES,
};
