const GET_COACHES_REQUEST = 'GET_COACHES_REQUEST';
const GET_COACHES_SUCCESS = 'GET_COACHES_SUCCESS';
const GET_COACHES_ERROR = 'GET_COACHES_ERROR';
const CLEANUP_COACHES = 'CLEANUP_COACHES';

export default {
  GET_COACHES_REQUEST,
  GET_COACHES_SUCCESS,
  GET_COACHES_ERROR,
  CLEANUP_COACHES,
}