const CONTACT_US_REQUEST = 'CONTACT_US_REQUEST';
const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
const CONTACT_US_ERROR = 'CONTACT_US_ERROR';
const CLEANUP_CONTACT_US = 'CLEANUP_CONTACT_US';

export default {
  CONTACT_US_REQUEST,
  CONTACT_US_SUCCESS,
  CONTACT_US_ERROR,
  CLEANUP_CONTACT_US,
};
