const GET_FITNES_DOMAINS_REQUEST = 'GET_FITNES_DOMAINS_REQUEST';
const GET_FITNES_DOMAINS_SUCCESS = 'GET_FITNES_DOMAINS_SUCCESS';
const GET_FITNES_DOMAINS_ERROR = 'GET_FITNES_DOMAINS_ERROR';
const CLEANUP_DOMAINS = 'CLEANUP_DOMAINS';

export default {
  GET_FITNES_DOMAINS_REQUEST,
  GET_FITNES_DOMAINS_SUCCESS,
  GET_FITNES_DOMAINS_ERROR,
  CLEANUP_DOMAINS,
};