const GET_ALL_EXERCISES_REQUEST = 'GET_ALL_EXERCISES_REQUEST';
const GET_ALL_EXERCISES_SUCCESS = 'GET_ALL_EXERCISES_SUCCESS';
const GET_ALL_EXERCISES_ERROR = 'GET_ALL_EXERCISES_ERROR';

const GET_MY_EXERCISES_REQUEST = 'GET_MY_EXERCISES_REQUEST';
const GET_MY_EXERCISES_SUCCESS = 'GET_MY_EXERCISES_SUCCESS';
const GET_MY_EXERCISES_ERROR = 'GET_MY_EXERCISES_ERROR';
const CLEANUP_EXERCISES = 'CLEANUP_EXERCISES';

const ADD_EXERCISE_REQUEST = 'ADD_EXERCISE_REQUEST';
const ADD_EXERCISE_SUCCESS = 'ADD_EXERCISE_SUCCESS';
const ADD_EXERCISE_ERROR = 'ADD_EXERCISE_ERROR';

const UPDATE_EXERCISE_REQUEST = 'UPDATE_EXERCISE_REQUEST';
const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS';
const UPDATE_EXERCISE_ERROR = 'UPDATE_EXERCISE_ERROR';

const REMOVE_EXERCISE_REQUEST = 'REMOVE_EXERCISE_REQUEST';
const REMOVE_EXERCISE_SUCCESS = 'REMOVE_EXERCISE_SUCCESS';
const REMOVE_EXERCISE_ERROR = 'REMOVE_EXERCISE_ERROR';

const GET_EXERCISE_REQUEST = 'GET_EXERCISE_REQUEST';
const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
const GET_EXERCISE_ERROR = 'GET_EXERCISE_ERROR';

const VOTE_EXERCISE_REQUEST = 'VOTE_EXERCISE_REQUEST';
const VOTE_EXERCISE_SUCCESS = 'VOTE_EXERCISE_SUCCESS';
const VOTE_EXERCISE_ERROR = 'VOTE_EXERCISE_ERROR';

const UNVOTE_EXERCISE_REQUEST = 'UNVOTE_EXERCISE_REQUEST';
const UNVOTE_EXERCISE_SUCCESS = 'UNVOTE_EXERCISE_SUCCESS';
const UNVOTE_EXERCISE_ERROR = 'UNVOTE_EXERCISE_ERROR';

export default {
  GET_ALL_EXERCISES_REQUEST,
  GET_ALL_EXERCISES_SUCCESS,
  GET_ALL_EXERCISES_ERROR,
  GET_MY_EXERCISES_REQUEST,
  GET_MY_EXERCISES_SUCCESS,
  GET_MY_EXERCISES_ERROR,
  CLEANUP_EXERCISES,
  ADD_EXERCISE_REQUEST,
  ADD_EXERCISE_SUCCESS,
  ADD_EXERCISE_ERROR,
  REMOVE_EXERCISE_REQUEST,
  REMOVE_EXERCISE_SUCCESS,
  REMOVE_EXERCISE_ERROR,
  GET_EXERCISE_REQUEST,
  GET_EXERCISE_SUCCESS,
  GET_EXERCISE_ERROR,
  UPDATE_EXERCISE_REQUEST,
  UPDATE_EXERCISE_SUCCESS,
  UPDATE_EXERCISE_ERROR,
  VOTE_EXERCISE_REQUEST,
  VOTE_EXERCISE_SUCCESS,
  VOTE_EXERCISE_ERROR,
  UNVOTE_EXERCISE_REQUEST,
  UNVOTE_EXERCISE_SUCCESS,
  UNVOTE_EXERCISE_ERROR,
};
