const GET_HOMEWORKS_REQUEST = 'GET_HOMEWORKS_REQUEST';
const GET_HOMEWORKS_SUCCESS = 'GET_HOMEWORKS_SUCCESS';
const GET_HOMEWORKS_ERROR = 'GET_HOMEWORKS_ERROR';
const UPDATE_HOMEWORK_REQUEST = 'UPDATE_HOMEWORK_REQUEST';
const UPDATE_HOMEWORK_SUCCESS = 'UPDATE_HOMEWORK_SUCCESS';
const UPDATE_HOMEWORK_ERROR = 'UPDATE_HOMEWORK_ERROR';
const CLEANUP_HOMEWORKS = 'CLEANUP_HOMEWORKS';

export default {
  GET_HOMEWORKS_REQUEST,
  GET_HOMEWORKS_SUCCESS,
  GET_HOMEWORKS_ERROR,
  UPDATE_HOMEWORK_REQUEST,
  UPDATE_HOMEWORK_SUCCESS,
  UPDATE_HOMEWORK_ERROR,
  CLEANUP_HOMEWORKS,
}