const GET_ALL_MEASUREMENTS_REQUEST = 'GET_ALL_MEASUREMENTS_REQUEST';
const GET_ALL_MEASUREMENTS_SUCCESS = 'GET_ALL_MEASUREMENTS_SUCCESS';
const GET_ALL_MEASUREMENTS_ERROR = 'GET_ALL_MEASUREMENTS_ERROR';

const CREATE_NEW_MEASUREMENT_REQUEST = 'CREATE_NEW_MEASUREMENT_REQUEST';
const CREATE_NEW_MEASUREMENT_SUCCESS = 'CREATE_NEW_MEASUREMENT_SUCCESS';
const CREATE_NEW_MEASUREMENT_ERROR = 'CREATE_NEW_MEASUREMENT_ERROR';

const UPDATE_MEASUREMENT_REQUEST = 'UPDATE_MEASUREMENT_REQUEST';
const UPDATE_MEASUREMENT_SUCCESS = 'UPDATE_MEASUREMENT_SUCCESS';
const UPDATE_MEASUREMENT_ERROR = 'UPDATE_MEASUREMENT_ERROR';

const CLEANUP_MEASUREMENTS = 'CLEANUP_MEASUREMENTS';

export default {
  GET_ALL_MEASUREMENTS_REQUEST,
  GET_ALL_MEASUREMENTS_SUCCESS,
  GET_ALL_MEASUREMENTS_ERROR,
  CREATE_NEW_MEASUREMENT_REQUEST,
  CREATE_NEW_MEASUREMENT_SUCCESS,
  CREATE_NEW_MEASUREMENT_ERROR,
  UPDATE_MEASUREMENT_REQUEST,
  UPDATE_MEASUREMENT_SUCCESS,
  UPDATE_MEASUREMENT_ERROR,
  CLEANUP_MEASUREMENTS,
};
