const GET_MEETINGS_REQUEST = 'GET_MEETINGS_REQUEST';
const GET_MEETINGS_SUCCESS = 'GET_MEETINGS_SUCCESS';
const GET_MEETINGS_ERROR = 'GET_MEETINGS_ERROR';
const CREATE_MEETING_REQUEST = 'CREATE_MEETING_REQUEST';
const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
const CREATE_MEETING_ERROR = 'CREATE_MEETING_ERROR';
const UPDATE_MEETING_REQUEST = 'UPDATE_MEETING_REQUEST';
const UPDATE_MEETING_SUCCESS = 'UPDATE_MEETING_SUCCESS';
const UPDATE_MEETING_ERROR = 'UPDATE_MEETING_ERROR';
const CLEANUP_MEETINGS = 'CLEANUP_MEETINGS';

export default {
  GET_MEETINGS_REQUEST,
  GET_MEETINGS_SUCCESS,
  GET_MEETINGS_ERROR,
  CREATE_MEETING_REQUEST,
  CREATE_MEETING_SUCCESS,
  CREATE_MEETING_ERROR,
  UPDATE_MEETING_REQUEST,
  UPDATE_MEETING_SUCCESS,
  UPDATE_MEETING_ERROR,
  CLEANUP_MEETINGS,
}