const GET_MEMBERS_REQUEST = 'GET_MEMBERS_REQUEST';
const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
const GET_MEMBERS_ERROR = 'GET_MEMBERS_ERROR';
const CLEANUP_MEMBERS = 'CLEANUP_MEMBERS';

export default {
  GET_MEMBERS_REQUEST,
  GET_MEMBERS_SUCCESS,
  GET_MEMBERS_ERROR,
  CLEANUP_MEMBERS,
}