const GET_MEMBER_RECOMMENDATION_SUCCESS = 'GET_MEMBER_RECOMMENDATION_SUCCESS';
const GET_MEMBER_RECOMMENDATION_ERROR = 'GET_MEMBER_RECOMMENDATION_ERROR';
const GET_MEMBER_RECOMMENDATION_REQUEST = 'GET_MEMBER_RECOMMENDATION_REQUEST';

export default {
  GET_MEMBER_RECOMMENDATION_SUCCESS,
  GET_MEMBER_RECOMMENDATION_ERROR,
  GET_MEMBER_RECOMMENDATION_REQUEST,
};
