const GET_MEMBER_PROFILE_REQUEST = 'GET_MEMBER_PROFILE_REQUEST';
const GET_MEMBER_PROFILE_SUCCESS = 'GET_MEMBER_PROFILE_SUCCESS';
const GET_MEMBER_PROFILE_ERROR = 'GET_MEMBER_PROFILE_ERROR';
const GET_SESSIONS_REQUEST = 'GET_SESSIONS_REQUEST';
const GET_SESSIONS_SUCCESS = 'GET_SESSIONS_SUCCESS';
const GET_SESSIONS_ERROR = 'GET_SESSIONS_ERROR';
const CLEANUP_MEMBER_PROFILE = 'CLEANUP_MEMBER_PROFILE';

export default {
  GET_MEMBER_PROFILE_REQUEST,
  GET_MEMBER_PROFILE_SUCCESS,
  GET_MEMBER_PROFILE_ERROR,
  GET_SESSIONS_REQUEST,
  GET_SESSIONS_SUCCESS,
  GET_SESSIONS_ERROR,
  CLEANUP_MEMBER_PROFILE,
}