const GET_MEMBER_CRF_SUCCESS = 'GET_MEMBER_CRF_SUCCESS';
const GET_MEMBER_CRF_ERROR = 'GET_MEMBER_CRF_ERROR';
const GET_MEMBER_CRF_REQUEST = 'GET_MEMBER_CRF_REQUEST';
const CALCULATE_MEMBER_CRF_REQUEST = 'CALCULATE_MEMBER_CRF_REQUEST';
const CALCULATE_MEMBER_CRF_SUCCESS = 'CALCULATE_MEMBER_CRF_SUCCESS';
const CALCULATE_MEMBER_CRF_ERROR = 'CALCULATE_MEMBER_CRF_ERROR';

export default {
  GET_MEMBER_CRF_SUCCESS,
  GET_MEMBER_CRF_ERROR,
  GET_MEMBER_CRF_REQUEST,
  CALCULATE_MEMBER_CRF_REQUEST,
  CALCULATE_MEMBER_CRF_SUCCESS,
  CALCULATE_MEMBER_CRF_ERROR,
};
