const SHOW_ERROR = 'SHOW_ERROR';
const CLEANUP_ERROR = 'CLEANUP_ERROR';
const SHOW_SUCCESS = 'SHOW_SUCCESS';
const CLEANUP_SUCCESS = 'CLEANUP_SUCCESS';

export default {
  SHOW_ERROR,
  CLEANUP_ERROR,
  SHOW_SUCCESS,
  CLEANUP_SUCCESS,
};
