const TOGGLE_NOTIFICATIONS_PANEL = 'TOGGLE_NOTIFICATIONS_PANEL';
const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';
const CLEANUP_NOTIFICATIONS = 'CLEANUP_NOTIFICATIONS';
const UPDATE_NOTIFICATION_REQUEST = 'UPDATE_NOTIFICATION_REQUEST';
const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
const UPDATE_NOTIFICATION_ERROR = 'UPDATE_NOTIFICATION_ERROR';
const DELETE_ALL_NOTIFICATIONS_REQUEST = 'DELETE_ALL_NOTIFICATIONS_REQUEST';
const DELETE_ALL_NOTIFICATIONS_SUCCESS = 'DELETE_ALL_NOTIFICATIONS_SUCCESS';
const DELETE_ALL_NOTIFICATIONS_ERROR = 'DELETE_ALL_NOTIFICATIONS_ERROR';

export default {
  TOGGLE_NOTIFICATIONS_PANEL,
  GET_NOTIFICATIONS_REQUEST,
  GET_NOTIFICATIONS_SUCCESS,
  GET_NOTIFICATIONS_ERROR,
  CLEANUP_NOTIFICATIONS,
  UPDATE_NOTIFICATION_REQUEST,
  UPDATE_NOTIFICATION_SUCCESS,
  UPDATE_NOTIFICATION_ERROR,
  DELETE_ALL_NOTIFICATIONS_REQUEST,
  DELETE_ALL_NOTIFICATIONS_SUCCESS,
  DELETE_ALL_NOTIFICATIONS_ERROR,
};
