const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';

const BOOK_COACH_REQUEST = 'BOOK_COACH_REQUEST';
const BOOK_COACH_SUCCESS = 'BOOK_COACH_SUCCESS';
const BOOK_COACH_ERROR = 'BOOK_COACH_ERROR';

const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
const CHECKOUT_ERROR = 'CHECKOUT_ERROR';

const ONE_TIME_CHECKOUT_REQUEST = 'ONE_TIME_CHECKOUT_REQUEST';
const ONE_TIME_CHECKOUT_SUCCESS = 'ONE_TIME_CHECKOUT_SUCCESS';
const ONE_TIME_CHECKOUT_ERROR = 'ONE_TIME_CHECKOUT_ERROR';

const CREATE_MEMBER_PROFILE_REQUEST = 'CREATE_MEMBER_PROFILE_REQUEST';
const CREATE_MEMBER_PROFILE_SUCCESS = 'CREATE_MEMBER_PROFILE_SUCCESS';
const CREATE_MEMBER_PROFILE_ERROR = 'CREATE_MEMBER_PROFILE_ERROR';

const UPDATE_MEMBER_PROFILE_REQUEST = 'UPDATE_MEMBER_PROFILE_REQUEST';
const UPDATE_MEMBER_PROFILE_SUCCESS = 'UPDATE_MEMBER_PROFILE_SUCCESS';
const UPDATE_MEMBER_PROFILE_ERROR = 'UPDATE_MEMBER_PROFILE_ERROR';

const UPDATE_PROFILE_DATA_REQUEST = 'UPDATE_PROFILE_DATA_REQUEST';
const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS';
const UPDATE_PROFILE_DATA_ERROR = 'UPDATE_PROFILE_DATA_ERROR';

const UPDATE_PROFILE_PASSWORD_REQUEST = 'UPDATE_PROFILE_PASSWORD_REQUEST';
const UPDATE_PROFILE_PASSWORD_SUCCESS = 'UPDATE_PROFILE_PASSWORD_SUCCESS';
const UPDATE_PROFILE_PASSWORD_ERROR = 'UPDATE_PROFILE_PASSWORD_ERROR';

const UPDATE_PROFILE_SOCIAL_LINKS_REQUEST = 'UPDATE_PROFILE_SOCIAL_LINKS_REQUEST';
const UPDATE_PROFILE_SOCIAL_LINKS_SUCCESS = 'UPDATE_PROFILE_SOCIAL_LINKS_SUCCESS';
const UPDATE_PROFILE_SOCIAL_LINKS_ERROR = 'UPDATE_PROFILE_SOCIAL_LINKS_ERROR';

const UPDATE_PROFILE_FITNESS_DOMAINS_REQUEST = 'UPDATE_PROFILE_FITNESS_DOMAINS_REQUEST';
const UPDATE_PROFILE_FITNESS_DOMAINS_SUCCESS = 'UPDATE_PROFILE_FITNESS_DOMAINS_SUCCESS';
const UPDATE_PROFILE_FITNESS_DOMAINS_ERROR = 'UPDATE_PROFILE_FITNESS_DOMAINS_ERROR';

const UPDATE_PROFILE_MEASUREMENTS_REQUEST = 'UPDATE_PROFILE_MEASUREMENTS_REQUEST';
const UPDATE_PROFILE_MEASUREMENTS_SUCCESS = 'UPDATE_PROFILE_MEASUREMENTS_SUCCESS';
const UPDATE_PROFILE_MEASUREMENTS_ERROR = 'UPDATE_PROFILE_MEASUREMENTS_ERROR';

const CREATE_BANK_ACCOUNT_ON_ONBOARDING_REQUEST = 'CREATE_BANK_ACCOUNT_ON_ONBOARDING_REQUEST';
const CREATE_BANK_ACCOUNT_ON_ONBOARDING_SUCCESS = 'CREATE_BANK_ACCOUNT_ON_ONBOARDING_SUCCESS';
const CREATE_BANK_ACCOUNT_ON_ONBOARDING_ERROR = 'CREATE_BANK_ACCOUNT_ON_ONBOARDING_ERROR';

const CREATE_BANK_ACCOUNT_REQUEST = 'CREATE_BANK_ACCOUNT_REQUEST';
const CREATE_BANK_ACCOUNT_SUCCESS = 'CREATE_BANK_ACCOUNT_SUCCESS';
const CREATE_BANK_ACCOUNT_ERROR = 'CREATE_BANK_ACCOUNT_ERROR';

const DESTROY_BANK_ACCOUNT_REQUEST = 'DESTROY_BANK_ACCOUNT_REQUEST';
const DESTROY_BANK_ACCOUNT_SUCCESS = 'DESTROY_BANK_ACCOUNT_SUCCESS';
const DESTROY_BANK_ACCOUNT_ERROR = 'DESTROY_BANK_ACCOUNT_ERROR';

const CHANGE_ONBOARDING_PROFILE = 'CHANGE_ONBOARDING_PROFILE';

const CLEANUP_PROFILE = 'CLEANUP_PROFILE';

export default {
  GET_USER_PROFILE_REQUEST,
  GET_USER_PROFILE_SUCCESS,
  GET_USER_PROFILE_ERROR,
  UPDATE_USER_PROFILE_REQUEST,
  UPDATE_USER_PROFILE_SUCCESS,
  UPDATE_USER_PROFILE_ERROR,
  BOOK_COACH_REQUEST,
  BOOK_COACH_SUCCESS,
  BOOK_COACH_ERROR,
  CHANGE_ONBOARDING_PROFILE,
  CLEANUP_PROFILE,
  CHECKOUT_REQUEST,
  CHECKOUT_SUCCESS,
  CHECKOUT_ERROR,
  ONE_TIME_CHECKOUT_REQUEST,
  ONE_TIME_CHECKOUT_SUCCESS,
  ONE_TIME_CHECKOUT_ERROR,
  CREATE_MEMBER_PROFILE_REQUEST,
  CREATE_MEMBER_PROFILE_SUCCESS,
  CREATE_MEMBER_PROFILE_ERROR,
  UPDATE_MEMBER_PROFILE_REQUEST,
  UPDATE_MEMBER_PROFILE_SUCCESS,
  UPDATE_MEMBER_PROFILE_ERROR,
  UPDATE_PROFILE_DATA_REQUEST,
  UPDATE_PROFILE_DATA_SUCCESS,
  UPDATE_PROFILE_DATA_ERROR,
  UPDATE_PROFILE_PASSWORD_REQUEST,
  UPDATE_PROFILE_PASSWORD_SUCCESS,
  UPDATE_PROFILE_PASSWORD_ERROR,
  UPDATE_PROFILE_SOCIAL_LINKS_REQUEST,
  UPDATE_PROFILE_SOCIAL_LINKS_SUCCESS,
  UPDATE_PROFILE_SOCIAL_LINKS_ERROR,
  UPDATE_PROFILE_FITNESS_DOMAINS_REQUEST,
  UPDATE_PROFILE_FITNESS_DOMAINS_SUCCESS,
  UPDATE_PROFILE_FITNESS_DOMAINS_ERROR,
  CREATE_BANK_ACCOUNT_ON_ONBOARDING_REQUEST,
  CREATE_BANK_ACCOUNT_ON_ONBOARDING_SUCCESS,
  CREATE_BANK_ACCOUNT_ON_ONBOARDING_ERROR,
  CREATE_BANK_ACCOUNT_REQUEST,
  CREATE_BANK_ACCOUNT_SUCCESS,
  CREATE_BANK_ACCOUNT_ERROR,
  DESTROY_BANK_ACCOUNT_REQUEST,
  DESTROY_BANK_ACCOUNT_SUCCESS,
  DESTROY_BANK_ACCOUNT_ERROR,
  UPDATE_PROFILE_MEASUREMENTS_REQUEST,
  UPDATE_PROFILE_MEASUREMENTS_SUCCESS,
  UPDATE_PROFILE_MEASUREMENTS_ERROR,
};
