const GET_PROGRAMS_REQUEST = 'GET_PROGRAMS_REQUEST';
const GET_PROGRAMS_SUCCESS = 'GET_PROGRAMS_SUCCESS';
const GET_PROGRAMS_ERROR = 'GET_PROGRAMS_ERROR';
const ADD_PROGRAM_REQUEST = 'ADD_PROGRAM_REQUEST';
const ADD_PROGRAM_SUCCESS = 'ADD_PROGRAM_SUCCESS';
const ADD_PROGRAM_ERROR = 'ADD_PROGRAM_ERROR';
const UPDATE_PROGRAM_REQUEST = 'UPDATE_PROGRAM_REQUEST';
const UPDATE_PROGRAM_SUCCESS = 'UPDATE_PROGRAM_SUCCESS';
const UPDATE_PROGRAM_ERROR = 'UPDATE_PROGRAM_ERROR';
const DELETE_PROGRAM_EXERCISE_REQUEST = 'DELETE_PROGRAM_EXERCISE_REQUEST';
const DELETE_PROGRAM_EXERCISE_SUCCESS = 'DELETE_PROGRAM_EXERCISE_SUCCESS';
const DELETE_PROGRAM_EXERCISE_ERROR = 'DELETE_PROGRAM_EXERCISE_ERROR';
const CLEANUP_PROGRAMS = 'CLEANUP_PROGRAMS';

export default {
  GET_PROGRAMS_REQUEST,
  GET_PROGRAMS_SUCCESS,
  GET_PROGRAMS_ERROR,
  ADD_PROGRAM_REQUEST,
  ADD_PROGRAM_SUCCESS,
  ADD_PROGRAM_ERROR,
  UPDATE_PROGRAM_REQUEST,
  UPDATE_PROGRAM_SUCCESS,
  UPDATE_PROGRAM_ERROR,
  DELETE_PROGRAM_EXERCISE_REQUEST,
  DELETE_PROGRAM_EXERCISE_SUCCESS,
  DELETE_PROGRAM_EXERCISE_ERROR,
  CLEANUP_PROGRAMS,
}