const GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST';
const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
const GET_REPORTS_ERROR = 'GET_REPORTS_ERROR';
const GET_REPORT_REQUEST = 'GET_REPORT_REQUEST';
const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
const GET_REPORT_ERROR = 'GET_REPORT_ERROR';
const GET_REPORT_QUESTIONS_REQUEST = 'GET_REPORT_QUESTIONS_REQUEST';
const GET_REPORT_QUESTIONS_SUCCESS = 'GET_REPORT_QUESTIONS_SUCCESS';
const GET_REPORT_QUESTIONS_ERROR = 'GET_REPORT_QUESTIONS_ERROR';
const REPORT_NOT_FOUND = 'REPORT_NOT_FOUND';
const UPDATE_REPORT_REQUEST = 'UPDATE_REPORT_REQUEST';
const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
const UPDATE_REPORT_ERROR = 'UPDATE_REPORT_ERROR';
const CLEANUP_REPORTS = 'CLEANUP_REPORTS';

export default {
  GET_REPORTS_REQUEST,
  GET_REPORTS_SUCCESS,
  GET_REPORTS_ERROR,
  GET_REPORT_REQUEST,
  GET_REPORT_SUCCESS,
  GET_REPORT_ERROR,
  GET_REPORT_QUESTIONS_REQUEST,
  GET_REPORT_QUESTIONS_SUCCESS,
  GET_REPORT_QUESTIONS_ERROR,
  REPORT_NOT_FOUND,
  UPDATE_REPORT_REQUEST,
  UPDATE_REPORT_SUCCESS,
  UPDATE_REPORT_ERROR,
  CLEANUP_REPORTS,
};
