const GET_WIDGET_REQUEST = 'GET_WIDGET_REQUEST';
const GET_WIDGET_SUCCESS = 'GET_WIDGET_SUCCESS';
const GET_WIDGET_ERROR = 'GET_WIDGET_ERROR';
const CLEANUP_WIDGET = 'CLEANUP_WIDGET';

export default {
  GET_WIDGET_REQUEST,
  GET_WIDGET_SUCCESS,
  GET_WIDGET_ERROR,
  CLEANUP_WIDGET,
};
