name: Front-end deploy

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Yarn Install
        run: |
          yarn
      
      - name: Yarn Build
        run: |
          yarn build